unstable_features = true
use_field_init_shorthand = true
newline_style = "Unix"
imports_granularity = "Crate"
use_small_heuristics = "Max"
reorder_imports = true
edition = "2021"
# This option will merge imports, however it's only available in +nightly.
# imports_granularity = "Module"
# fn_args_density = "Compressed"
# overflow_delimited_expr = "true"
